CREATE TABLE GRAO_SOJA (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data_registro DATE DEFAULT SYSDATE,
    tipo_cultura VARCHAR2(50),
    peso_toneladas NUMBER(5,2),
    caminhao_id NUMBER,
    CONSTRAINT fk_caminhao FOREIGN KEY (caminhao_id) REFERENCES CAMINHAO (id)
);


CREATE TABLE GRAO_SOJA (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data_registro DATE DEFAULT SYSDATE,
    tipo_cultura VARCHAR2(50),
    peso_toneladas NUMBER(5,2),
    caminhao_id NUMBER,
    CONSTRAINT fk_caminhao FOREIGN KEY (caminhao_id) REFERENCES CAMINHAO (id)
);

